import type { NextPage } from 'next'
import Head from 'next/head'
import BodySingle from "dh-marvel/components/layouts/body/single/body-single";
import { Hero, HeroAPIResponse } from 'types';
import Comics from 'dh-marvel/components/Comics/Comics';


// const Index: NextPage<{data : HeroAPIResponse}> = ({data} : {data : HeroAPIResponse}) => {
const Index: NextPage = () => {

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <BodySingle title={"Comics"}>
                <Comics/>
            </BodySingle >
        </>
    )
}


export default Index